<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC8-DX-6PKDH92" ignored="0" name="Test2" tests="1" failures="1" timestamp="18 Jul 2018 05:09:13 GMT" time="36.064" errors="0">
  <testcase name="testlogin" time="36.021" classname="Test2.Project_GITHUB">
    <failure type="java.lang.AssertionError" message="expected [Sign in to GitHub . GitHub] but found [GitHub]">
      <![CDATA[java.lang.AssertionError: expected [Sign in to GitHub . GitHub] but found [GitHub]
at Test2.Project_GITHUB.testlogin(Project_GITHUB.java:38)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testlogin -->
</testsuite> <!-- Test2 -->
